name: Build Android Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # =========================
      # DECODE KEYSTORE
      # =========================
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # =========================
      # VERIFY KEYSTORE
      # =========================
      - name: Verify Keystore
        run: |
          keytool -list -v \
          -keystore android/app/upload-keystore.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Install Dependencies
        run: npm install

      - name: Build Vite
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      # =========================
      # BUILD SIGNED AAB  - name: Build Release AAB
      # =========================
      - name: Build Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # =========================
      # UPLOAD AAB
      # =========================
     # - name: Upload AAB
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release
          path: android/app/build/outputs/bundle/release/*.apk
           # path: android/app/build/outputs/bundle/release/*.aab