name: Build Android Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      # =========================
      # CHECKOUT
      # =========================
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # SETUP NODE
      # =========================
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # =========================
      # SETUP JAVA
      # =========================
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # =========================
      # DECODE KEYSTORE
      # =========================
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # =========================
      # VERIFY KEYSTORE
      # =========================
      - name: Verify Keystore
        run: |
          keytool -list -v \
          -keystore android/app/upload-keystore.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }}

      # =========================
      # INSTALL DEPENDENCIES
      # =========================
      - name: Install Dependencies
        run: npm install

      # =========================
      # BUILD VITE
      # =========================
      - name: Build Vite
        run: npm run build

      # =========================
      # SYNC CAPACITOR
      # =========================
      - name: Sync Capacitor
        run: npx cap sync android

      # =========================
      # BUILD SIGNED APK
      # =========================
      - name: Build Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # =========================
      # UPLOAD APK
      # =========================
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release
          path: android/app/build/outputs/apk/release/*.apk
      - name: Verify ADI File
      # =========================
      # Varify APK
      # =========================
      run: |
        unzip -l android/app/build/outputs/apk/release/app-release.apk | grep adi-registration.properties    